### ISSUE TITLE
Token not provided 

### ISSUE THREAD

**Issue by sallespro** [nightwolfz/inferno-starter#14]
hi, didn't succeed with the starter.
db fixture needed ? 

```
  app:forbidden TypeError: Token not provided
  app:forbidden     at /home/user/inferno-starter/src/server/routes/account.js:76:27
```

**Comment by nightwolfz** [comment]
@sallespro That just means you are not logged in. Create an account and login :-)

**Comment by sallespro** [comment]
Its not rendering the App to do so

Em 19 de dez de 2016 7:31 PM, "Ryan M." <notifications@github.com> escreveu:

**Comment by nightwolfz** [comment]
Can you pull in the latest version and try with a clean `npm install` ? (a new inferno version beta37 was released 1 hour ago)

I don't know why but I'm not seeing any problems here

**Comment by sallespro** [comment]
from a fresh install,
`npm run dev`

## server

```
[nodemon] starting `node index.js`
  app:static /home/user/inferno-starter/build +0ms
  app:start Listening on port 2000 +47ms
  webpack:compiler Running on port 2002 +3ms
         Asset     Size  Chunks             Chunk Names
     bundle.js   665 kB       0  [emitted]  bundle
    bundle.css  4.17 kB       0  [emitted]  bundle
 bundle.js.map   735 kB       0  [emitted]  bundle
bundle.css.map  12.1 kB       0  [emitted]  bundle
webpack: bundle is now VALID.
  app:forbidden Token not provided +12s
```

`npm run prod`

## browser

`Uncaught SyntaxError: Unexpected token <` at bundle.js:1

## server
```
> cross-env NODE_ENV=production node index.js

  server:webpack Environment: Production +0ms
  app:static /home/user/inferno-starter/build +4s
  app:start Listening on port 2000 +72ms
Time: 12107ms
         Asset     Size  Chunks             Chunk Names
     bundle.js   149 kB       0  [emitted]  bundle
    bundle.css  4.17 kB       0  [emitted]  bundle
bundle.css.map  12.1 kB       0  [emitted]  bundle
  webpack:compiler Finished compiling +8s
  app:forbidden Token not provided +46s
```

**Comment by nightwolfz** [comment]
@sallespro Thanks! I think I've found the issue. Pull and give it a try!

**Comment by sallespro** [comment]
prod works now !

**Comment by flieks** [comment]
Hi there,

For me this not works.
i get 
forbidden Token not provided
request to http://localhost:2000/api/todos failed, reason: socket hang up

full output:
```
[nodemon] starting `node index.js`
  app:static C:\Users\gebruiker\Documents\projects\EXPS\website\inferno-starter-master\build +0ms
  app:start Listening on port 2000 +39ms
  webpack:compiler Running on port 2002 +5ms
         Asset     Size  Chunks             Chunk Names
     bundle.js   666 kB       0  [emitted]  bundle
    bundle.css  4.17 kB       0  [emitted]  bundle
 bundle.js.map   739 kB       0  [emitted]  bundle
bundle.css.map  12.1 kB       0  [emitted]  bundle
webpack: bundle is now VALID.
  app:forbidden Token not provided +4m
  app:forbidden Token not provided +3s
  app:error FetchError: request to http://localhost:2000/api/todos failed, reason: socket hang up
  app:error     at ClientRequest.<anonymous> (C:\Users\gebruiker\Documents\projects\EXPS\website\inferno-starter-master\node_modules\node-fetch\index.js:133:11)
  app:error     at emitOne (events.js:96:13)
  app:error     at ClientRequest.emit (events.js:188:7)
  app:error     at Socket.socketOnEnd (_http_client.js:344:9)
  app:error     at emitNone (events.js:91:20)
  app:error     at Socket.emit (events.js:185:7)
  app:error     at endReadableNT (_stream_readable.js:973:12)
  app:error     at _combinedTickCallback (internal/process/next_tick.js:74:11)
  app:error     at process._tickCallback (internal/process/next_tick.js:98:9) +2m
  app:error FetchError: request to http://localhost:2000/api/todos failed, reason: socket hang up
  app:error     at ClientRequest.<anonymous> (C:\Users\gebruiker\Documents\projects\EXPS\website\inferno-starter-master\node_modules\node-fetch\index.js:133:11)
  app:error     at emitOne (events.js:96:13)
  app:error     at ClientRequest.emit (events.js:188:7)
  app:error     at Socket.socketOnEnd (_http_client.js:344:9)
  app:error     at emitNone (events.js:91:20)
  app:error     at Socket.emit (events.js:185:7)
  app:error     at endReadableNT (_stream_readable.js:973:12)
  app:error     at _combinedTickCallback (internal/process/next_tick.js:74:11)
  app:error     at process._tickCallback (internal/process/next_tick.js:98:9) +3s
  app:forbidden Token not provided +11ms
```

**Comment by nightwolfz** [comment]
@flieks Maybe it's your firewall ?

**Comment by flieks** [comment]
thanks, suddenly it worked (i think it was a inferno-redux issue)
