### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bind' of undefined    

### ISSUE THREAD

**Issue by scottburch** [nightwolfz/inferno-starter#17]
Thanks for sharing inferno-starter.  It appears to be exactly what I am looking for.

However, I get this loading any page.  Here is the stack trace.  It appears to be due to inferno-devtools not being loaded in client.js before the first Inferno.render.  If I move up the require, then the error goes away.

Uncaught TypeError: Cannot read property 'bind' of undefined
    at createReactCompositeComponent (http://localhost:2002/build/bundle.js:3389:42)
    at updateReactComponent (http://localhost:2002/build/bundle.js:3306:23)
    at createReactCompositeComponent (http://localhost:2002/build/bundle.js:3393:29)
    at updateReactComponent (http://localhost:2002/build/bundle.js:3306:23)
    at createReactCompositeComponent (http://localhost:2002/build/bundle.js:3393:29)
    at updateReactComponent (http://localhost:2002/build/bundle.js:3306:23)
    at http://localhost:2002/build/bundle.js:3321:110
    at Array.map (native)
    at normalizeChildren (http://localhost:2002/build/bundle.js:3321:80)
    at createReactDOMComponent (http://localhost:2002/build/bundle.js:3350:39)

**Comment by scottburch** [comment]
I forgot to say where this error occurs.  It appears to be when inferno tries to pass through forceUpdate().

**Comment by scottburch** [comment]
I just figured out that this has something to do with devtools

**Comment by nightwolfz** [comment]
@scottburch Thanks for reporting this, I updated the code.
