### ISSUE TITLE
logger has already been declared

### ISSUE THREAD

**Issue by p-adams** [nightwolfz/inferno-starter#6]
When I try to npm run dev I get this error:

             const logger  = require('debug')
             ^
             SyntaxError: Identifier 'logger' has already been declared

**Comment by nightwolfz** [comment]
@p-adams That's very odd, can you pull the latest `master` and if it happens again, give me more info ?

**Comment by p-adams** [comment]
I cloned repo, did an npm install and here is the result from npm run dev:

$ npm run dev

> inferno-starter@0.5.0 dev C:\Users\paadams\inferno-starter
> cross-env NODE_ENV=development nodemon index.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: C:\Users\paadams\inferno-starter\src\server/*_/_ src/shared
[nodemon] starting `node index.js`
C:\Users\paadams\inferno-starter\src\client\stores.js:27
const stores = exports.stores = (state = {}, token) => {
                                       ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at loader (C:\Users\paadams\inferno-starter\node_modules\babel-register\lib\                                                                                            node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js](C:Userspaadams                                                                                            inferno-starternode_modulesbabel-registerlibnode.js:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:/Users/paadams/inferno-starter/src/server/middlewar                                                                                            e/context.js:2:1)
    at Module._compile (module.js:409:26)
    at loader (C:\Users\paadams\inferno-starter\node_modules\babel-register\lib\                                                                                            node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js](C:Userspaadams                                                                                            inferno-starternode_modulesbabel-registerlibnode.js:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by nightwolfz** [comment]
Very strange, I wonder what it could be...

Can you try these:
1. Make sure you are running node v6 or newer.
2. Delete the following line from `.babelrc`:

```
"runtimePattern": "index\\.js",
```

If `npm run dev` still doesn't work, see if `npm run prod` does.

I will see if I can reproduce the issue later today. 
Let me know what OS and what node version you are running, thanks @p-adams  !

**Comment by p-adams** [comment]
I upgrade my version of node and the errors a gone now. What port should the app be running on?

Thanks!

**Comment by nightwolfz** [comment]
Glad that helped! :)

Port 2000.

You can configure it in `inferno-starter/src/server/config.js`
