### ISSUE TITLE
Error on npm run dev 

### ISSUE THREAD

**Issue by joshua1** [nightwolfz/inferno-starter#9]
Hi @nightwolfz ,
after running ```npm install``` to install packages, i ran ```npm run dev``` and got the error below
```/Users/user/Documents/Sycamore labs/Ajala3/node_modules/babel-plugin-inferno/lib/index.js:182
                        props.map(({ astName, astValue, astSpread }) =>
                                   ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Module._extensions..js (module.js:405:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/user/Documents/Sycamore labs/Ajala3/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /Users/user/Documents/Sycamore labs/Ajala3/node_modules/babel-core/lib/transformation/file/options/option-manager.js:174:20
    at Array.map (native)
[nodemon] app crashed - waiting for file changes before starting...```

**Comment by joshua1** [comment]
I went past this by upgrading npm to 6.9 , but ran into a different issue with node-sass 
```ERROR in ./src/assets/css/index.scss
Module build failed: ModuleBuildError: Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/user/Documents/Sycamore labs/Ajala3/node_modules/node-sass/vendor' ```
node-sass does not have a vendor directory that seems to have been referenced somewhere

**Comment by joshua1** [comment]
I think the issues i had here was with my trying to use yarn in place of npm for module updates

**Comment by nightwolfz** [comment]
I see. I had some weird things happen when using `npm` and `yarn` interchangeably on some projects too unfortunately.
